name: Analyse SonarCloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup SonarCloud
        uses: SonarSource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=TaranDiallo_mastersicsorbonne
            -Dsonar.organization=diallousmane
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
